### PR TITLE
added instructions for installing Albacore into conda env

### PR DESCRIPTION
**Pull request by kapsakcj**
Hi @Psy-Fer , I love what you're that you are collecting tips/tricks/hacks for working with Nanopore data. I'm currently wading through a sea of fresh Nanopore data so this is very useful! Thanks!

I've added instructions for installing Albacore into a conda environmnent. I've run into issues when installing Albacore via Ubuntu/debian `apt-get` route. Conda makes things easy and may be useful to new users looking to run Albacore from the command line!

If I learn of other tips/tricks/hacks I'll try to post them here!

Curtis

### CODE REVIEW

**Review by Psy-Fer — APPROVED** [review]
Thanks so much. I'll ad this  in, then throw in some Attribution. Would you like your real name added? or just keep it at your GitHub name?

**Comment by Psy-Fer** [comment]
Hmm, well your full name is on your GitHub...silly me. I'll add both :)

**Comment by kapsakcj** [comment]
Real name and github name would be great. Helps for an early-career bioinformatician. Thanks!

**Comment by Psy-Fer** [comment]
Done!

**Pull request merged**
